name: daka

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 21 * * *'

jobs:
  sign:
    runs-on: windows-2019
    steps:
      - name: Checkout #同步仓库
        uses: actions/checkout@v2
      - name: Set up Python #安装python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.10
      - name: Install requests #安装requests
        run: |
          pip3 install requests
          pip3 install ddddocr
          pip3 install wcwidth
          python xiaoren2.py
      

